### ISSUE TITLE
Add Ninsight Unconfirmed UTXOs to bch-js

### ISSUE THREAD

**Issue by christroutner** [Permissionless-Software-Foundation/bch-js#11]
This is a specific task that is associated with [this top level task](https://github.com/Permissionless-Software-Foundation/bounties/issues/3)

The scope of this task is to port the [BITBOX.Address.unconfirmed() function](https://github.com/Bitcoin-com/bitbox-sdk/blob/master/lib/Address.ts#L316-L346) to the [Ninsight library in bch-js](https://github.com/Permissionless-Software-Foundation/bch-js/blob/master/src/ninsight.js). 

Porting the code should meet the following requirements:
- The code should follow the same pattern as the existing [utxo() method](https://github.com/Permissionless-Software-Foundation/bch-js/blob/master/src/ninsight.js#L33-L99), but should only use the POST call to the REST API. This should also include api-doc documentation.
- A unit test with mocking should be included. You can follow the same pattern of the [utxo unit test](https://github.com/Permissionless-Software-Foundation/bch-js/blob/master/test/unit/ninsight.js#L16-L80)

## Acceptance Criteria
The bounty will be paid out upon successful acceptance of a Pull Request (PR) into this repository. The PR must include the following:
- Add a `unconfirmed()` method to the [Ninsight class library](https://github.com/Permissionless-Software-Foundation/bch-js/blob/master/src/ninsight.js).
- The new method should include api-doc documentation.
- Add [unit tests](https://github.com/Permissionless-Software-Foundation/bch-js/blob/master/test/unit/ninsight.js)

**Comment by zh** [comment]
Created ticket for this task in Trello

**Comment by christroutner** [comment]
150 tokens awarded to Stoyan for Ninsight unconfirmed UTXO endpoint added to bch-js. F1 on spreadsheet. TXID:
621538666fb94f87c2f1b3b8f038b7ca2afcde1355ad7248ab0dca01e76c1d01

This issue resolved by this PR:
https://github.com/Permissionless-Software-Foundation/bch-js/pull/50
