### ISSUE TITLE
HDNode.derivePath broken?

### ISSUE THREAD

**Issue by mariusk** [Permissionless-Software-Foundation/bch-js#15]
I get an error message about function being undefined. 

Inside the actual source code of HDNode's class definition inside `hdnode.js`, there's this nugget:
```javascript
derivePath(hdnode, path) {
    return hdnode.derivePath(path)
  }
```
Assuming `hdnode` it an instance of the same class, this would effectively mean we're trying to call `"somePath".derivePath()` when we're doing `hdnode.derivePath(hdnode, 'somePath')`, or even `hdnode.derivePath('somePath')` directly, which fails for obvious reasons.

https://github.com/Permissionless-Software-Foundation/bch-js/blob/d2c999f739461cd5c784e7218505eaa864746c94/src/hdnode.js#L381

**Comment by mariusk** [comment]
I think maybe it needs to call `.derive(path)` instead.

**Comment by mariusk** [comment]
Looking at the `bitbox-sdk` source, it has the same patterns, but the `hdnode` parameter is not the same class as is being defined in `hdnode.js`, so I guess that is where my confusion comes from.

**Comment by christroutner** [comment]
Here is an example on how to send BCH with bch-js:
https://github.com/Permissionless-Software-Foundation/bch-js-examples/blob/master/applications/wallet/send-bch/send-bch.js

The HDNode class is instantiated when the bch-js class is instantiated:
https://github.com/Permissionless-Software-Foundation/bch-js/blob/d2c999f739461cd5c784e7218505eaa864746c94/src/bch-js.js#L91

That same approach is taken by most of the sub-classes within the bch-js library.

I don't fully understand what your question is? Can you clarify?

**Comment by mariusk** [comment]
Could you show an example of using `derivePath` with `HDNode`? The examples from the docs, or even from how it's done with the `bitbox-sdk` doesn't seem to work.

**Comment by christroutner** [comment]
The example that I linked to previously has an example of using `HDNode.derivePath()`:

https://github.com/Permissionless-Software-Foundation/bch-js-examples/blob/master/applications/wallet/send-bch/send-bch.js#L155-L158

**Comment by mariusk** [comment]
I'm running pretty much that code. Works with the bitbox api, but not this one.

**Comment by christroutner** [comment]
I don't know what to tell you. The code in the examples directory works. It uses the function that you asked about.

**Comment by mariusk** [comment]
I probably got a bit confused about which functions were async and which were not. In the end I managed to set up and get access to my previously created wallet successfully. I've attached my example code at the end of this comment. My main pain points were:

* Wrong/faulty rest URLs (which one to use, which ones require API keys, certificate errors for at least one)
* Method sync or async confusion (from docs, which I believe is wrong in a couple of places)
* Generating testnet addresses. Since `bchjs` gets initialized with this info, I did not immediately understand that I had to pass `testnet` to the `.fromSeed` method to get a proper testnet address

Thanks for your patience anyway.

```javascript
// Set NETWORK to either testnet or mainnet
const NETWORK = 'testnet';

import BCHJS from '@psf/bch-js';

// REST API servers.
const MAINNET_API_FREE = 'https://tapi.fullstack.cash/v3/';
const TESTNET_API_FREE = 'https://tapi.fullstack.cash/v3/';

let bchjs;
if (NETWORK === 'mainnet')
  bchjs = new BCHJS({ restURL: MAINNET_API_FREE })
else
  bchjs = new BCHJS({
    restURL: TESTNET_API_FREE
  });

const mnemonic = 'INSERT OR GENERATE YOUR OWN MNEMONIC HERE ...';

async function getWallet() {
  const rootSeed = await bchjs.Mnemonic.toSeed(mnemonic);
  const masterHDNode = bchjs.HDNode.fromSeed(rootSeed, NETWORK);
  return masterHDNode;
}

async function getBalance(masterHDNode) {
  for (let i = 0; i < 1; i++) {
    const PATH = `m/44'/1'/0'/0/${i}`;
    const childNode = bchjs.HDNode.derivePath(masterHDNode, PATH);
    const cashAddress = bchjs.HDNode.toCashAddress(childNode);

    const adrType = bchjs.Address.detectAddressType(cashAddress);
    const isTestNet  = bchjs.Address.isTestnetAddress(cashAddress);
    console.log('generated cashAddress:', adrType, isTestNet, cashAddress);
    try {
      const balance = await bchjs.Blockbook.balance(cashAddress);
      console.log('balance:', balance);
    } catch(err) {
      console.error('i', i, err);
    }
  }
}

async function main() {
  const masterHDNode = await getWallet();
  await getBalance(masterHDNode);
};

main();
```
