### ISSUE TITLE
Unable to connect to bch testnet. :  https://testnet3.fullstack.cash/v4/

### ISSUE THREAD

**Issue by SachinSWN** [Permissionless-Software-Foundation/bch-js#200]
Testnet3 REST API server: https://testnet3.fullstack.cash/v4/, Seems down, Using which testnet url I can use for testing?

**Comment by christroutner** [comment]
FullStack.cash no longer provides testnet support. It was expensive to operate, very few people use it, and no one pays for it. Testnet is often disrupted by miners, which makes it impossible to do dev work. Also, the rules are so different on testnet, that it often sets devs back when they things that worked on testnet fail to work on mainnet.

Most developers use micro-transacitons on mainnet, or use tokens, if i they need to simulate large quantities.

I'm not aware of any other service that offers access to testnet.
